patches:
  boat-placement-only-water: true
  no-bedrock: true
  no-illegals: true
  piston-dupe: true
  kill-command: true
  negative-items: true
  anti-void-fall: true
scan-negative-container-items: true

website:
  enabled: true
  port: 8080
  title: "2b2t"
  message: ""