name: VoidUtils
version: '${project.version}'
main: net.utils.voidutils.VoidUtils
commands:
  kill:
    description: Instantly kill yourself
    usage: /kill
  uptime:
    description: Shows how long the server has been running
